# Generated by Django 5.2.3 on 2025-06-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data da Despesa')),
                ('categoria', models.CharField(choices=[('Compra de Pelúcias', 'Compra de Pelúcias'), ('Reparo de Máquinas', 'Reparo de Máquinas'), ('Transporte', 'Transporte'), ('Manutencao Geral', 'Manutenção Geral'), ('Aluguel', 'Aluguel'), ('Outros', 'Outros')], default='Outros', max_length=50, verbose_name='Categoria')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('paga', models.BooleanField(default=True, verbose_name='Paga')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data', 'categoria'],
            },
        ),
    ]
