# Generated by Django 5.2.3 on 2025-06-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Receita')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data da Receita')),
                ('origem', models.CharField(choices=[('Maquina', 'Venda em Máquina'), ('Pix', 'Pix Direto'), ('Dinheiro', 'Dinheiro em Espécie'), ('Outros', 'Outros Ganhos')], default='Maquina', max_length=50, verbose_name='Origem')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-data'],
            },
        ),
    ]
