# Generated by Django 5.2.3 on 2025-06-14 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_receita'),
        ('maquinas', '0001_initial'),
        ('pelucias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1, verbose_name='Quantidade Vendida')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Venda Unitário')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Venda')),
                ('forma_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Forma de Pagamento')),
                ('maquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maquinas.maquina', verbose_name='Máquina')),
                ('pelucia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pelucias.pelucia', verbose_name='Pelúcia Vendida')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_venda'],
            },
        ),
    ]
