# Generated by Django 5.2.3 on 2025-06-14 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pelucias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=50, unique=True, verbose_name='Identificação da Máquina')),
                ('localizacao', models.CharField(max_length=200, verbose_name='Localização')),
                ('status', models.CharField(choices=[('Operacional', 'Operacional'), ('Reparo', 'Em Reparo'), ('Manutencao', 'Em Manutenção'), ('Inativa', 'Inativa')], default='Operacional', max_length=20, verbose_name='Status')),
                ('data_instalacao', models.DateField(auto_now_add=True, verbose_name='Data de Instalação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('capacidade_pelucias', models.IntegerField(default=100, verbose_name='Capacidade de Pelúcias')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['localizacao', 'identificacao'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade de Pelúcias')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('pelucia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelucias.pelucia')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='maquinas.maquina')),
            ],
            options={
                'verbose_name': 'Estoque da Máquina',
                'verbose_name_plural': 'Estoques das Máquinas',
                'unique_together': {('maquina', 'pelucia')},
            },
        ),
    ]
