# Generated by Django 5.2.3 on 2025-06-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelucia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Pelúcia')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo')),
                ('estoque_total', models.IntegerField(default=0, verbose_name='Estoque Total')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Pelúcia',
                'verbose_name_plural': 'Pelúcias',
                'ordering': ['nome'],
            },
        ),
    ]
